### ISSUE TITLE
Make a blog for announcements

### ISSUE THREAD

**Issue by treyhunner** [editorconfig/editorconfig.github.com#49]
As discussed in #48 by [Hong](https://github.com/editorconfig/editorconfig.github.com/pull/48#issuecomment-110113975).

**Comment by xuhdev** [comment]
I think we can do it either with WordPress or a static site generator.

WordPress:

Pros:

- Longer history, well supported (don't expect it die in 10 years);
- many themes;
- don't rely on a third party to have a commenting system.

Cons:

- self maintenance unless we pay;
- not easy to track in a code repository.

Current popular static site generators are on the contrary. I'm mostly worried about the supporting of a static site generator, besides that, I don't think the other downsides really make a deal -- we probably don't need commenting.

**Comment by treyhunner** [comment]
Another alternative: [Ghost](https://ghost.org/)

**Comment by jedmao** [comment]
I've used Ghost and I'm very happy with it.

**Comment by xuhdev** [comment]
We can go with [Nikola](http://getnikola.com) which is what I'm using for my blog (I'm more familiar with), but not as popular as [pelican](http://getpelican.com), which is used by kernel.org (thus don't expect it to die soon).

**Comment by jedmao** [comment]
Ghost has a better design aesthetic IMO.

**Comment by treyhunner** [comment]
We use pelican for pythonsd.org and I am not a fan (at least not of the version we're using).

I'm fine with any of these options.  I do not plan to produce much content for the blog, but it would be nice to have for short announcement posts if for nothing else.  Allowing posting from community members occasionally might be nice, but I don't think it's a strictly necessary feature.

**Comment by xuhdev** [comment]
Yes, I suppose we would only use it for announcement

**Comment by ffes** [comment]
Since the site is hosted at Github Pages, why not use Jekylls blog features. If you like that idea, I have a fairly straightforward patch/PR to add blog posts to the current website.

Pros:
* Easy integration in the current site
* Just add a markdown/html file to `_posts`. See https://jekyllrb.com/docs/posts/
* No need to maintain the blog software/users login/etc
* Everybody can new posts with a GitHub Pull Request.
* No comments to blog posts (moderating)

Cons:
* No comments to blog posts (user interaction)

To test locally, you need to have Jekyll installed, but that is quite easy IMHO
